--
-- TOC entry 197 (class 1259 OID 217906)
-- Name: servico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.servico (
    id bigint NOT NULL,
    horas_banheiro integer NOT NULL,
    horas_cozinha integer NOT NULL,
    horas_outros integer NOT NULL,
    horas_quarto integer NOT NULL,
    horas_quintal integer NOT NULL,
    horas_sala integer NOT NULL,
    icone character varying(14) NOT NULL,
    nome character varying(50) NOT NULL,
    porcentagem_comissao numeric(19,2) NOT NULL,
    posicao integer NOT NULL,
    qtd_horas integer NOT NULL,
    valor_banheiro numeric(19,2) NOT NULL,
    valor_cozinha numeric(19,2) NOT NULL,
    valor_minimo numeric(19,2) NOT NULL,
    valor_outros numeric(19,2) NOT NULL,
    valor_quarto numeric(19,2) NOT NULL,
    valor_quintal numeric(19,2) NOT NULL,
    valor_sala numeric(19,2) NOT NULL
);


ALTER TABLE public.servico OWNER TO postgres;

--
-- TOC entry 196 (class 1259 OID 217904)
-- Name: servico_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.servico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.servico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 2820 (class 0 OID 217906)
-- Dependencies: 197
-- Data for Name: servico; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.servico (id, horas_banheiro, horas_cozinha, horas_outros, horas_quarto, horas_quintal, horas_sala, icone, nome, porcentagem_comissao, posicao, qtd_horas, valor_banheiro, valor_cozinha, valor_minimo, valor_outros, valor_quarto, valor_quintal, valor_sala) FROM stdin;
4	3	3	3	3	3	3	TWF_CLEANING_3	servico 3	3.00	3	3	3.00	3.00	3.00	3.00	3.00	3.00	3.00
5	4	4	4	4	4	4	TWF_CLEANING_1	servico 4	12.00	4	4	4.00	4.00	4.00	4.00	4.00	4.00	4.00
3	2	2	2	2	2	2	TWF_CLEANING_2	servico 2	25.00	2	2	2.00	2.00	2.00	2.00	2.00	2.00	2.00
6	12	12	12	12	12	12	TWF_CLEANING_1	serviço 5	12.12	2	12	1.22	12.12	12.12	12.12	12.12	12.12	12.12
1	12	12	12	1222	12	12	TWF_CLEANING_1	servico 1	12.00	21	1	12.00	12.00	150.00	12.00	12.00	12.00	12.00
\.

--
-- TOC entry 2829 (class 0 OID 0)
-- Dependencies: 196
-- Name: servico_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.servico_id_seq', 7, true);

--
-- TOC entry 2693 (class 2606 OID 217910)
-- Name: servico servico_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.servico
    ADD CONSTRAINT servico_pkey PRIMARY KEY (id);